// eslint-disable-next-line import/no-nodejs-modules -- validates committed release metadata in Node-based CI
import { readFileSync } from 'node:fs'

import {
  projectDistributionFeedCatalog,
  verifyAndParseDistributionFeed,
} from './distributionFeed'

describe('generated distribution metadata', () => {
  // `modules/catalog-v1.json` is still published for clients that shipped
  // before the signed Feed. It is generated by `scripts/distribution.mjs` from
  // the same Feed, so both projections must describe exactly the same catalog.
  it('is signed by the client trust root and matches the old-client projection', () => {
    const feed = verifyAndParseDistributionFeed(
      readFileSync('distribution/feed-v1.json'),
      readFileSync('distribution/feed-v1.sig', 'utf8').trim(),
    )
    const projected = JSON.parse(
      JSON.stringify(projectDistributionFeedCatalog(feed)),
    ) as unknown
    const committedCatalog = JSON.parse(
      readFileSync('modules/catalog-v1.json', 'utf8'),
    ) as unknown

    expect(committedCatalog).toEqual(projected)
  })
})
